#!/bin/bash

# this tests a local package
# every commit has to pass this test

# run with ./np-test-local [path/to/dir]
# or np-test-local after installing
# TODO: maybe add adaptivity, fenics development version, ...

# name of the package
P=nanopores

if [ ! -z $1 ]; then
    cd $1
fi

echo Testing locally installed package.

# check for $P directory
if [ ! -d $P ]; then
    echo "ERROR: This script has to be called from a directory containing a local '$P' package."
    exit
fi

# adjust path for importing pkgs
export PYTHONPATH=$PWD:$PYTHONPATH
echo "Importing $P from
$(python -c "import $P
print $P.INSTALLDIR")
"

for file in $P/testsuite/test*.py; do
    echo Executing $file
    python $file
    echo
done
echo Tests completed.
