 function createfigure(X, Y, Z)
     
 
 
%  Auto-generated by MATLAB on 10-Mar-2016 17:58:25

% Create figure
 figure1 = figure;
% 
% %Create axes
axes1 = axes('Parent',figure1);
view(axes1,[322.5 30]);
box(axes1,'on');
hold(axes1,'all');
xlim([0 20])
ylim([0 20])
zlim([0 20])

% % Create plot3
plot3(X,Y,Z,'MarkerSize',12,'Marker','o','LineWidth',2,'LineStyle','none','Color','blue');
 
 end